### PR TITLE
fix: create duplicate OAuth connection data

### LINKED ISSUE #17: Create duplicate OAuth connection data
Repeated use of the API to get access tokens through OAuth code, the backend will create multiple OAuth connection data in the database.

image

### PR DESCRIPTION
**Pull request by SiongSng**
# Description

Fix create duplicate OAuth connection data.
Add tests for these fixes.

Fixes #17 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by banahaker — DISMISSED** [review]
lOoK gOoD

File: src/router/api/authentication/util.ts [hunk 1]
```diff
@@ -31,6 +31,7 @@ export async function connectOAuthAccount(
   const accountInfo = await accessInfo.getAccountInfo(oauth.accountType);
   const accountAlreadyExists = await User.exists({ email: accountInfo.email });
 
+  // If the account not exists, create a new user.
```
Comment (lumynou5) [inline src/router/api/authentication/util.ts]:
```suggestion
  // If the account doesn't exist, create a new user.
```

**Review by lumynou5 — CHANGES_REQUESTED** [review]

**Review by lumynou5 — APPROVED** [review]
